### ISSUE TITLE
Ss icon dark mode

### ISSUE THREAD

**Issue by cbigart** [ForgeCreative/shiftcase#11]
When you select the menubar app icon in dark mode it turns to black instead of staying white. 

This isn't crucial for launch but figured I would add it here just in case it is easy.

<img width="503" alt="screen shot 2019-01-24 at 5 29 35 pm" src="https://user-images.githubusercontent.com/17996482/51712702-a52eb780-1ffd-11e9-9a28-b1cc2e814850.png">

**Comment by mariodev12** [comment]
I can use the same icon for dark mode, its easy.

**Comment by cbigart** [comment]
Great!!

**Comment by cbigart** [comment]
Im pretty sure this is fixed, closing task
